Repository AY2324S2-CS2103T-T10-3/tp, pull requests merged in 2024-04, with the labels that each got.

#84 Implement the export command
  .gitignore
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/export/PersonDataExporter.java
  src/main/java/seedu/address/export/PersonExporter.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/export/MockPersonDataExporter.java
  src/test/java/seedu/address/export/PersonDataExporterTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/InviteCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: enhancement

#86 Add event date
  codecov.yml
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/resources/view/EventListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/address/storage/JsonSerializableEventBookTest.java
  src/test/java/seedu/address/testutil/EditEventDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EventBuilder.java
Labels: enhancement

#165 Fix EventDate to account for leap year
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/EventDate.java
Labels: bug

#171 Fix Select Event DG
  docs/DeveloperGuide.md
  docs/diagrams/SelectEventSequenceDiagram -- Logic.puml
  docs/images/SelectEventSequenceDiagram-Logic.png
  docs/package-lock.json
  docs/package.json
Labels: documentation

#175 Modify UI Class Diagram
  docs/diagrams/UiClassDiagram.puml
  src/main/resources/images/UiClassDiagram.png
Labels: documentation

#168 GUI error for result display box with delete command
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
Labels: bug

#179 Update delete and export command in UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: documentation

#185 Update formatting
  docs/DeveloperGuide.md
  docs/diagrams/FindPersonSequenceDiagram.puml
Labels: documentation

#186 Fix UG links
  docs/UserGuide.md
Labels: documentation

#187 Include length recommendation in Ug
  docs/UserGuide.md
Labels: documentation

#188 Update developer guide and sequence diagram for export
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
  docs/images/ExportSequenceDiagram.png
Labels: documentation

#194 Update ug image and dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/addev.png
  docs/images/afterFind.png
  docs/images/afterSel.png
  docs/images/afterinvite.png
  docs/images/beforeFind.png
  docs/images/beforeSel.png
  docs/images/beforeaddev.png
  docs/images/beforeinvite.png
Labels: documentation

#192 Update use cases
  docs/DeveloperGuide.md
Labels: documentation

#197 Update export warning message
  docs/UserGuide.md
Labels: documentation
